version: "3.3"
services:
  api-server:
    build: .
    container_name: api-server
    networks:
      - backendnet
    ports:
      - "2020:2020"
networks:
  backendnet:
    external:
      name: backendnet
