version: "3.3"
services:
  api-server:
    build: .
    container_name: api-server
    env_file: .env
    environment:
      MONGO_ADD_CHAINBOARDDBUSER_USERNAME: ${MONGO_ADD_CHAINBOARDDBUSER_USERNAME}
      MONGO_ADD_CHAINBOARDDBUSER_PASSWORD: ${MONGO_ADD_CHAINBOARDDBUSER_PASSWORD}
    ports:
      - "2020:2020"
      - "4040:4040"