version: "3.3"
services:
  api-server:
    build: .
    container_name: api-server
    env_file: .env
    environment:
      MONGO_ADD_CHAINBOARDDBUSER_USERNAME: ${MONGO_ADD_CHAINBOARDDBUSER_USERNAME}
      MONGO_ADD_CHAINBOARDDBUSER_PASSWORD: ${MONGO_ADD_CHAINBOARDDBUSER_PASSWORD}
    networks:
      - backendnet
    ports:
      - "2020:2020"
      - "4040:4040"
      - "3030:3030"
networks:
  backendnet:
    external:
      name: backendnet
