version: "3.3"
services:
  api-server:
    build: .
    container_name: api-server
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backendnet
    ports:
      - "2020:2020"
      - "3030:3030"
      - "4040:4040"
networks:
  backendnet:
    external:
      name: backendnet
