version: "3.3"
services:
  mongodb:
    image: mongo:3.6.0
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
