version: "3.3"
services:
  mongodb:
    image: mongo:3.6.0
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks: 
      - backendnet 
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
networks: 
  backendnet: 
    external: 
      name: backendnet 

volumes:
  mongodb-data:
